# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('societe', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('emailAdress', models.EmailField(max_length=254, verbose_name='adresse email du client')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('date_embauche', models.DateTimeField(verbose_name="date d'embauche")),
            ],
        ),
        migrations.CreateModel(
            name='Mission_en_cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutMission', models.DateTimeField(verbose_name='date de debut de mission')),
                ('poste', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cra.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Mission_terminee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutMission', models.DateTimeField(verbose_name='date de debut de mission')),
                ('poste', models.CharField(max_length=200)),
                ('dateFinMission', models.DateTimeField(verbose_name='date de fin de mission')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cra.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('employe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cra.Employe')),
            ],
            bases=('cra.employe',),
        ),
        migrations.AddField(
            model_name='mission_terminee',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cra.Consultant'),
        ),
        migrations.AddField(
            model_name='mission_en_cours',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cra.Consultant'),
        ),
    ]
