# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('employe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cra.Employe')),
            ],
            bases=('cra.employe',),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=200)),
                ('dateDebutMission', models.DateTimeField(verbose_name=b'date de debut de mission')),
                ('dateFinMission', models.DateTimeField(verbose_name=b'date de fin de mission')),
            ],
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateTimeField(verbose_name=b"date d'embauche"),
        ),
    ]
