# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '0002_auto_20160505_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('societe', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('emailAdress', models.EmailField(max_length=254, verbose_name=b'adresse email du client')),
            ],
        ),
    ]
