# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '0003_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='dateFinMission',
        ),
    ]
