# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '0005_commercial2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='liste_clients',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='liste_consultants',
        ),
    ]
