# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '0006_auto_20160515_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='liste_clients',
            field=models.ManyToManyField(blank=True, null=True, to='cra.Client'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='liste_consultants',
            field=models.ManyToManyField(blank=True, null=True, to='cra.Consultant'),
        ),
    ]
