# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '0008_auto_20160515_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='liste_consultants',
            field=models.ManyToManyField(blank=True, null=True, related_name='liste_consultants', to='cra.Consultant'),
        ),
    ]
